language: r

sudo: required

warnings_are_errors: true

before_install: echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile

r_check_args: --as-cran --run-dontrun

r_packages:
   - covr

r_binary_packages:
  - ade4
  - ape
  - aRxiv
  - assertthat
  - bibtex
  - bitops
  - bold
  - caTools
  - chron
  - coda
  - colorspace
  - corpcor
  - cubature
  - data.table
  - DBI
  - dichromat
  - dplyr
  - foreach
  - formatR
  - fulltext
  - ggplot2
  - gtable
  - highr
  - iterators
  - knitr
  - labeling
  - lubridate
  - markdown
  - MCMCglmm
  - munsell
  - NLP
  - phylobase
  - plyr
  - R.cache
  - R.methodsS3
  - R.oo
  - R.utils
  - RColorBrewer
  - rcrossref
  - readxl
  - rentrez
  - reshape
  - reshape2
  - rjson
  - rmarkdown
  - RNeXML
  - rplos
  - rredis
  - scales
  - slam
  - solr
  - taxize
  - tensorA
  - tidyr
  - tm
  - uuid
  - XML
  - yaml

r_github_packages:
   - fmichonneau/rncl

after_success:
   - Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: chYOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
