language: r

sudo: required

warnings_are_errors: true

before_install: echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile

r_check_args: --as-cran --run-dontrun

r_packages:
  - covr

r_github_packages:
  - fmichonneau/rncl

after_success:
   - Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
