language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile

install:
  - ./pkg-build.sh install_github fmichonneau/rncl
  - ./pkg-build.sh install_r covr
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs


# language: r

# sudo: required

# warnings_are_errors: true

# before_install: echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile


# r_check_args: --as-cran --run-dontrun

# r_packages:
#   - covr

# r_github_packages:
#   - fmichonneau/rncl

after_success:
   - Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: chYOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=

env:
  global:
    - R_CHECK_ARGS="--as-cran --run-dontrun"
   matrix:
     #- RVERSION=oldrel
     - RVERSION=release
     - RVERSION=devel
